config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "static#game"
  get "leaderboard", to: "profile#index", as: "leaderboard"
  get "challenge", to: "static#challenge", as: "challenge"
  
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "profile", to: redirect("/leaderboard"), as: :profiles_path
  resources :profile
  
  resources :elements
  scope :api do
    defaults format: :json do
      get "craft", to: "api#craft"
    end
  end

  authenticated :user, lambda { |u| u.admin? } do
    namespace :admin do
      resources :badges
      resources :discoveries
      resources :discovery_recipes
      resources :elements
      resources :recipes
      resources :users
      resources :user_badges

      root to: "badges#index"
    end
  end
end

app/views/shared/_flash.html.erb
<% if notice %>
  <p class="notice p-4 bg-yellow-100"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert  bg-red-300"><%= alert %></p>
<% end %>

app/views/shared/_nav.html.erb
<nav class="p-4 rounded-lg bg-white shadow-lg underline space-x-4 max-w-screen-lg w-full">
  <%= render partial: "shared/nav_left" %>
  <div class="float-right">
    <%= render partial: "shared/nav_right" %>
  </div>
</nav>

app/views/shared/_nav_left.html.erb
  <%= link_to "Sandbox", root_path %>
  <%= link_to "Challenge", challenge_path %>
  <%= link_to "Leaderboard", leaderboard_path %>
  <% if current_user.present? %>
    <%= link_to "My Profile", profile_path(current_user) %>
  <% end %>

app/views/shared/_nav_mobile.html.erb
<details class="relative group">
  <summary class="absolute top-0 right-0 list-none group-open:p-2 cursor-pointer">
    <div class="group-open:hidden p-1 bg-white shadow-lg rounded mt-1 mr-1">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="h-6 w-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5"></path>
      </svg>
    </div>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="hidden h-6 w-6 group-open:block" x-show="menu">
      <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12"></path>
    </svg> 
  </summary>
  <nav class="flex flex-col gap-1 pt-2 p-4 pr-12 rounded-lg bg-white shadow-lg underline">
    <%= render partial: "shared/nav_left" %>
    <div class="h-2 flex items-center justify-center">
      <hr class="absolute right-4 left-4">
    </div>
    <%= render partial: "shared/nav_right" %>
  </nav>
</details>

app/views/shared/_nav_right.html.erb
<% if current_user.present? %>
  <% if current_user.admin? %>
    <%= link_to "Admin", admin_root_path, class: "inline underline" %>
  <% end %>
  <%= button_to "Sign Out", destroy_user_session_path, method: :delete, form_class: "inline", class: "underline" %>
<% else %>
  <%= link_to "Sign In", new_user_session_path, class: "inline underline" %>
  <%= link_to "Sign Up", new_user_registration_path, class: "inline underline" %>
<% end %>